# Registering New Diagnostic Functions

In [1]:
%load_ext autoreload
%autoreload 2

import os
os.chdir('/glade/u/home/fengzhu/Github/x4c/docsrc/notebooks')
import x4c
print(x4c.__version__)

2025.6.22


In [4]:
dirpath = '/glade/campaign/univ/ubrn0018/fengzhu/CESM_output/timeseries/b.e13.B1850C5.ne16_g16.icesm131_d18O_fixer.Miocene.3xCO2.005'
case = x4c.Timeseries(dirpath, grid_dict={'atm': 'ne16np4'})

>>> case.root_dir: /glade/campaign/univ/ubrn0018/fengzhu/CESM_output/timeseries/b.e13.B1850C5.ne16_g16.icesm131_d18O_fixer.Miocene.3xCO2.005
>>> case.path_pattern: comp/proc/tseries/*/casename.hstr.vn.timespan.nc
>>> case.grid_dict: {'atm': 'ne16np4', 'ocn': 'g16', 'lnd': 'ne16np4', 'rof': 'ne16np4', 'ice': 'g16'}
>>> case.casename: b.e13.B1850C5.ne16_g16.icesm131_d18O_fixer.Miocene.3xCO2.005
>>> case.vars_info created


## A 1st order variable that exists under the CESM Postprocessing Timeseries directory

In [5]:
spell = 'TS'
case.calc(spell)
case.diags[spell]

>>> case.ds["TS"] created
>>> case.diags["TS"] created


<xarray.DataArray 'TS' (time: 600, ncol: 13826)> Size: 33MB
array([[30.723846, 30.15387 , 29.340027, ..., 20.610352, 17.8833  ,
        18.761658],
       [31.421326, 31.069   , 30.561584, ..., 19.588074, 17.21759 ,
        18.28897 ],
       [31.425201, 31.07251 , 30.54779 , ..., 19.613098, 18.46637 ,
        19.39978 ],
       ...,
       [25.155579, 24.095459, 22.823944, ..., 29.183075, 27.860046,
        28.439423],
       [27.179352, 26.204254, 24.977203, ..., 25.29721 , 22.786072,
        23.526276],
       [29.186981, 28.433838, 27.424072, ..., 21.56839 , 19.447754,
        20.136566]], shape=(600, 13826), dtype=float32)
Coordinates:
  * time     (time) object 5kB 8951-01-31 00:00:00 ... 9000-12-31 00:00:00
    lat      (ncol) float64 111kB -35.26 -35.98 -37.07 ... 37.91 37.91 36.74
    lon      (ncol) float64 111kB 315.0 316.6 319.1 320.6 ... 132.5 137.5 135.0
Dimensions without coordinates: ncol
Attributes:
    units:         °C
    long_name:     Surface temperature (radiative)
    cell_methods:  time: mean
    path:          /glade/campaign/univ/ubrn0018/fengzhu/CESM_output/timeseri...
    gw:            <xarray.DataArray 'area' (ncol: 13826)> Size: 111kB\narray...
    lat:           <xarray.DataArray 'lat' (ncol: 13826)> Size: 111kB\n[13826...
    lon:           <xarray.DataArray 'lon' (ncol: 13826)> Size: 111kB\n[13826...
    comp:          atm
    grid:          ne16np4

## A deduced variable based on 1st order variables

In [16]:
spell = 'SST'
case.calc(spell)
case.diags[spell]

>>> case.ds["SST"] created
>>> case.diags["SST"] created


<xarray.DataArray 'SST' (time: 600, nlat: 384, nlon: 320)> Size: 295MB
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]],
      shape=(600, 384, 320), dtype=float32)
Coordinates:
    TLAT     (nlat, nlon) float64 983kB -87.73 -87.72 -87.7 ... 72.52 72.52
    TLONG    (nlat, nlon) float64 983kB 341.6 342.9 344.2 ... 326.2 326.5 326.8
    ULAT     (nlat, nlon) float64 983kB -87.53 -87.52 -87.5 ... 72.64 72.64
    ULONG    (nlat, nlon) float64 983kB 343.5 344.8 346.1 ... 326.4 326.7 327.0
  * time     (time) object 5kB 8951-01-31 00:00:00 ... 9000-12-31 00:00:00
Dimensions without coordinates: nlat, nlon
Attributes:
    long_name:     Sea Surface Temperature
    units:         °C
    grid_loc:      3111
    cell_methods:  time: mean z_t: mean
    path:          /glade/campaign/univ/ubrn0018/fengzhu/CESM_output/timeseri...
    gw:            <xarray.DataArray 'TAREA' (nlat: 384, nlon: 320)> Size: 98...
    lat:           <xarray.DataArray 'TLAT' (nlat: 384, nlon: 320)> Size: 983...
    lon:           <xarray.DataArray 'TLONG' (nlat: 384, nlon: 320)> Size: 98...
    dz:            <xarray.DataArray 'dz' ()> Size: 4B\n[1 values with dtype=...
    comp:          ocn
    grid:          g16

In [11]:
spell = 'd18Op'
case.calc(spell)
case.diags[spell]

>>> Spell `d18Op` is already calculated and the calculation is skipped.


<xarray.DataArray 'd18Op' (time: 600, ncol: 13826)> Size: 33MB
array([[-3.9242506, -4.0639043, -4.1208863, ..., -9.632945 , -8.070588 ,
        -8.230329 ],
       [-5.675137 , -5.547166 , -5.905688 , ..., -8.86035  , -8.010567 ,
        -7.663846 ],
       [-4.2343736, -4.4196844, -4.8832297, ..., -7.989228 , -7.1674585,
        -6.616235 ],
       ...,
       [-4.006505 , -4.380405 , -5.3446293, ..., -5.651295 , -5.3805113,
        -5.291581 ],
       [-3.416419 , -4.7590733, -4.9126744, ..., -8.602322 , -6.9465637,
        -6.7592263],
       [-3.531158 , -3.5579205, -3.6706924, ..., -8.005201 , -7.1768165,
        -6.878078 ]], shape=(600, 13826), dtype=float32)
Coordinates:
  * time     (time) object 5kB 8951-01-31 00:00:00 ... 9000-12-31 00:00:00
    lat      (ncol) float64 111kB -35.26 -35.98 -37.07 ... 37.91 37.91 36.74
    lon      (ncol) float64 111kB 315.0 316.6 319.1 320.6 ... 132.5 137.5 135.0
Dimensions without coordinates: ncol
Attributes:
    units:         permil
    long_name:     Precipitation d18O
    cell_methods:  time: mean
    path:          /glade/campaign/univ/ubrn0018/fengzhu/CESM_output/timeseri...
    gw:            <xarray.DataArray 'area' (ncol: 13826)> Size: 111kB\narray...
    lat:           <xarray.DataArray 'lat' (ncol: 13826)> Size: 111kB\n[13826...
    lon:           <xarray.DataArray 'lon' (ncol: 13826)> Size: 111kB\n[13826...
    comp:          atm
    grid:          ne16np4

## User-defined derived variables

In [13]:
x4c.diags.Registry.funcs

{'SST': <function x4c.diags.__autoreload_class__.get_SST(case, **kws)>,
 'SSS': <function x4c.diags.__autoreload_class__.get_SSS(case, **kws)>,
 'LST': <function x4c.diags.__autoreload_class__.get_LST(case, **kws)>,
 'MLD': <function x4c.diags.__autoreload_class__.get_MLD(case, **kws)>,
 'PRECT': <function x4c.diags.__autoreload_class__.get_PRECT(case, **kws)>,
 'dD': <function x4c.diags.__autoreload_class__.get_dD(case, **kws)>,
 'd18Op': <function x4c.diags.__autoreload_class__.get_d18Op(case, **kws)>,
 'd18Osw': <function x4c.diags.__autoreload_class__.get_d18Osw(case, **kws)>,
 'd18Oc': <function x4c.diags.__autoreload_class__.get_d18Oc(case, **kws)>,
 'RESTOM': <function x4c.diags.__autoreload_class__.get_RESTOM(case, **kws)>,
 'MOC': <function x4c.diags.__autoreload_class__.get_MOC(case, **kws)>,
 'ICEFRAC': <function x4c.diags.__autoreload_class__.get_ICEFRAC(case, **kws)>,
 'H2O': <function __main__.get_H2O(case, **kws)>}

In [16]:
@x4c.diags.F
def get_H2O(case, **kws):
    case.load('PRECRC_H2Or', **kws)
    case.load('PRECSC_H2Os', **kws)
    case.load('PRECRL_H2OR', **kws)
    case.load('PRECSL_H2OS', **kws)
    h2o = case.ds['PRECRC_H2Or'].x.da + case.ds['PRECSC_H2Os'].x.da + case.ds['PRECRL_H2OR'].x.da + case.ds['PRECSL_H2OS'].x.da
    h2o = h2o.where(h2o > 1e-18, 1e-18)
    h2o.name = 'H2O'
    h2o.attrs['long_name'] = 'H2O'
    h2o.attrs['units'] = 'kg m-2 s-1'
    return h2o

spell = 'H2O'
case.calc(spell)
case.diags['H2O']

>>> H2O is a supported derived variable.
>>> case.ds["PRECRC_H2Or"] created
>>> case.ds["PRECSC_H2Os"] created
>>> case.ds["PRECRL_H2OR"] created
>>> case.ds["PRECSL_H2OS"] created
>>> case.diags["H2O"] created


<xarray.DataArray 'H2O' (time: 600, ncol: 13826)> Size: 33MB
array([[5.9710459e-08, 5.6131434e-08, 3.5063369e-08, ..., 8.2408604e-08,
        6.4620174e-08, 7.5481097e-08],
       [4.0521218e-08, 3.6814747e-08, 3.6393399e-08, ..., 6.5435664e-08,
        7.0613574e-08, 7.7968416e-08],
       [6.7629379e-08, 5.5269446e-08, 5.4387058e-08, ..., 7.9079484e-08,
        6.8865539e-08, 5.6272302e-08],
       ...,
       [3.2595743e-08, 2.9543061e-08, 3.3436432e-08, ..., 6.5426519e-08,
        6.6881306e-08, 6.7055808e-08],
       [3.3392933e-08, 2.8302054e-08, 3.0985717e-08, ..., 1.0833849e-07,
        8.9037734e-08, 9.0263221e-08],
       [3.4362358e-08, 2.7343230e-08, 2.2276403e-08, ..., 9.4255995e-08,
        8.6246700e-08, 8.6356387e-08]], shape=(600, 13826), dtype=float32)
Coordinates:
  * time     (time) object 5kB 8951-01-31 00:00:00 ... 9000-12-31 00:00:00
    lat      (ncol) float64 111kB -35.26 -35.98 -37.07 ... 37.91 37.91 36.74
    lon      (ncol) float64 111kB 315.0 316.6 319.1 320.6 ... 132.5 137.5 135.0
Dimensions without coordinates: ncol
Attributes:
    units:         kg m-2 s-1
    long_name:     H2O
    cell_methods:  time: mean
    path:          /glade/campaign/univ/ubrn0018/fengzhu/CESM_output/timeseri...
    gw:            <xarray.DataArray 'area' (ncol: 13826)> Size: 111kB\narray...
    lat:           <xarray.DataArray 'lat' (ncol: 13826)> Size: 111kB\n[13826...
    lon:           <xarray.DataArray 'lon' (ncol: 13826)> Size: 111kB\n[13826...
    comp:          atm
    grid:          ne16np4